// Package names provides deterministic human-readable name generation.
// Names are generated by hashing input parts with SHA-256 and using
// the hash as an index into adjective and noun word lists, producing
// names like "salty-aardvark" or "brave-falcon".
package names

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"strings"
)

// Generate produces a deterministic human-readable name from the given parts.
// The parts are joined with "/" and hashed with SHA-256. The first 8 bytes of
// the hash are used to pick an adjective and the next 8 bytes pick a noun.
// Same inputs always produce the same name.
func Generate(parts ...string) string {
	input := strings.Join(parts, "/")
	hash := sha256.Sum256([]byte(input))

	adjIdx := binary.BigEndian.Uint64(hash[0:8]) % uint64(len(adjectives))
	nounIdx := binary.BigEndian.Uint64(hash[8:16]) % uint64(len(nouns))

	return fmt.Sprintf("%s-%s", adjectives[adjIdx], nouns[nounIdx])
}

// adjectives is a curated list of short, memorable adjectives.
var adjectives = []string{
	"able", "acid", "aged", "angry", "apt", "azure", "basic", "best",
	"big", "bitter", "black", "blaze", "bliss", "blue", "bold", "brave",
	"brief", "bright", "broad", "brisk", "brown", "calm", "cedar",
	"chief", "chill", "civic", "civil", "clean", "clear", "close",
	"cold", "cool", "coral", "cozy", "crisp", "cross", "curly", "cyan",
	"daily", "damp", "dark", "dawn", "dear", "deep", "dense", "dim",
	"dry", "dual", "dull", "dusty", "eager", "early", "easy", "elite",
	"empty", "epic", "equal", "even", "extra", "faded", "fair", "fast",
	"fine", "firm", "first", "fixed", "flat", "fleet", "fond", "frank",
	"free", "fresh", "full", "fun", "giant", "glad", "glow", "gold",
	"good", "grand", "gray", "great", "green", "grim", "handy", "happy",
	"hard", "harsh", "hazel", "heavy", "high", "holy", "honey", "hot",
	"huge", "humid", "icy", "idle", "inner", "iron", "jade", "joint",
	"jolly", "just", "keen", "kind", "known", "large", "last", "late",
	"lean", "left", "level", "light", "lime", "live", "local", "lone",
	"long", "lost", "loud", "low", "loyal", "lucky", "lunar", "lush",
	"magic", "main", "major", "maple", "merry", "mild", "mint", "misty",
	"mixed", "moist", "moody", "moral", "muddy", "muted", "naive",
	"narrow", "naval", "near", "neat", "neon", "new", "next", "nice",
	"nimble", "noble", "north", "noted", "novel", "nutty", "oaken",
	"odd", "olive", "only", "open", "outer", "pale", "past", "pearl",
	"petty", "pink", "plain", "plum", "polar", "prime", "proud", "pure",
	"quick", "quiet", "rare", "raw", "real", "red", "rich", "rigid",
	"ripe", "rocky", "rosy", "rough", "round", "royal", "ruby", "rude",
	"rusty", "safe", "sage", "salty", "sandy", "sharp", "shiny", "short",
	"shy", "silky", "slim", "slow", "small", "smart", "smoky", "snowy",
	"soft", "solar", "solid", "south", "spare", "spicy", "stark", "steep",
	"still", "stone", "stout", "sweet", "swift", "tall", "tangy", "teal",
	"thick", "thin", "tidy", "tight", "tiny", "total", "tough", "true",
	"urban", "upper", "usual", "valid", "vast", "vivid", "vocal", "warm",
	"wavy", "weak", "weary", "west", "white", "whole", "wide", "wild",
	"wise", "witty", "woody", "young", "zesty",
}

// nouns is a curated list of short, memorable nouns (mostly animals and nature).
var nouns = []string{
	"ant", "ape", "arch", "ash", "atlas", "aurora", "badge", "bark",
	"bass", "bay", "beam", "bear", "bell", "berry", "birch", "blade",
	"bloom", "bolt", "bone", "book", "bow", "branch", "breeze", "brick",
	"bridge", "brook", "brush", "bud", "bull", "cedar", "chain", "charm",
	"claw", "clay", "cliff", "cloud", "coast", "coil", "cone", "coral",
	"core", "crane", "creek", "crest", "crow", "crown", "crush", "cub",
	"cuff", "dart", "dawn", "deer", "delta", "dew", "dingo", "dock",
	"dove", "drift", "drum", "duck", "dune", "dust", "eagle", "earth",
	"edge", "elm", "ember", "fable", "falcon", "fawn", "fern", "field",
	"finch", "fire", "fish", "flame", "flare", "flint", "flora", "foam",
	"fog", "forge", "fork", "fort", "fox", "frost", "gale", "gate",
	"gem", "glen", "globe", "goat", "grain", "grape", "grass", "grove",
	"gull", "gust", "hare", "hawk", "hazel", "heath", "hedge", "heron",
	"hill", "hive", "holly", "horse", "hound", "ice", "iris", "ivory",
	"ivy", "jade", "jay", "jewel", "kale", "keel", "kelp", "kite",
	"knoll", "lake", "lark", "latch", "leaf", "ledge", "lily", "lime",
	"lion", "lodge", "lotus", "lynx", "maple", "marsh", "mesa", "mink",
	"mint", "moose", "moss", "moth", "mouse", "mule", "nest", "newt",
	"north", "oak", "oasis", "ocean", "olive", "onyx", "orbit", "orchid",
	"osprey", "otter", "owl", "palm", "panda", "path", "peach", "peak",
	"pearl", "pebble", "perch", "pike", "pine", "plain", "plume", "pond",
	"pony", "poppy", "port", "prism", "pulse", "quail", "quartz", "rain",
	"raven", "ray", "reed", "reef", "ridge", "ring", "river", "robin",
	"rock", "root", "rose", "rush", "sage", "sand", "seed", "shade",
	"shark", "shell", "shore", "silk", "slate", "slope", "snail", "snow",
	"solar", "south", "spark", "spire", "spray", "spring", "spruce",
	"star", "steam", "steel", "stone", "storm", "stork", "sun", "surge",
	"swan", "swift", "thorn", "tide", "tiger", "torch", "trail", "tree",
	"trout", "tulip", "tusk", "vale", "vapor", "vault", "veil", "verse",
	"vine", "viper", "voice", "wave", "whale", "wheat", "wheel", "wind",
	"wing", "wolf", "wren", "yew", "zebra", "zone",
}
